version: "3.9"
services:
  service:
    build: .
    ports:
      - 8080:8080
    environment:
      - JDBC_PASSWORD={DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    volumes:
      - ./pg_data:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5